#!/usr/bin/env python3
"""
Gawrsh! This script converts CSV tables to LaTeX format!
It reads all the CSV tables from results folders and creates beautiful LaTeX tables.
Ah-hyuck, sometimes the tables whisper their secrets in the formatting...
"""

import pandas as pd
import argparse
from pathlib import Path


def format_p_value_with_stars(p_val_str):
    """Format p-value strings with significance stars"""
    # Handle case where p-value might already have stars
    if '*' in str(p_val_str):
        return str(p_val_str)

    try:
        p_val = float(p_val_str)
        p_str = f"{p_val:.2e}"
        if p_val < 0.001:
            return f"{p_str}***"
        elif p_val < 0.01:
            return f"{p_str}**"
        elif p_val < 0.05:
            return f"{p_str}*"
        else:
            return p_str
    except (ValueError, TypeError):
        return str(p_val_str)


def process_csv_to_latex(csv_path, output_dir, table_config):
    """Process a single CSV file to LaTeX format"""
    print(f"Processing: {csv_path}")

    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"Error reading {csv_path}: {e}")
        return

    if df.empty:
        print(f"Empty CSV file: {csv_path}")
        return

    # Apply table-specific formatting
    formatted_df = df.copy()

    # Format p-values if they exist
    if 'p-value' in formatted_df.columns:
        formatted_df['p-value'] = formatted_df['p-value'].apply(format_p_value_with_stars)

    # Escape % symbols for LaTeX
    for col in formatted_df.columns:
        if '% Change' in col or 'Change' in col:
            formatted_df = formatted_df.rename(columns={col: col.replace('%', '\\%')})

    # delete speedup column if it exists
    if 'Speedup' in formatted_df.columns:
        formatted_df = formatted_df.drop(columns=['Speedup'])

    # delete t-statistic column if it exists
    if 't-statistic' in formatted_df.columns:
        formatted_df = formatted_df.drop(columns=['t-statistic'])

    # delete Time columns
    for col in formatted_df.columns:
        if 'Time' in col:
            formatted_df = formatted_df.drop(columns=[col])

    # round percentage change columns to 2 decimal places
    for col in formatted_df.columns:
        if '% Change' in col:
            formatted_df[col] = formatted_df[col].apply(lambda x: f"{x:.1f}" if pd.notnull(x) else x)

    # round time columns to 4 decimal places
    for col in formatted_df.columns:
        if 'Time' in col:
            formatted_df[col] = formatted_df[col].apply(lambda x: f"{x:.4f}" if pd.notnull(x) else x)

    # Generate LaTeX
    latex_table = formatted_df.to_latex(
        index=False,
        escape=False,
        longtable=True,
        caption=table_config['caption'],
        label=table_config['label'],
        column_format=table_config.get('column_format', None)
    )

    # Save individual LaTeX file
    latex_filename = csv_path.stem + '.tex'
    latex_path = output_dir / latex_filename

    with open(latex_path, 'w') as f:
        f.write(latex_table)

    print(f"LaTeX table saved to: {latex_path}")

    return {
        'name': csv_path.stem,
        'caption': table_config['caption'],
        'latex_content': latex_table,
        'section_title': table_config['section_title']
    }


def create_consolidated_latex_document(table_data, output_dir):
    """Create a consolidated LaTeX document with all tables"""
    latex_file = output_dir / "all_tables_consolidated.tex"

    with open(latex_file, 'w') as f:
        # Write LaTeX document header
        f.write("\\documentclass{article}\n")
        f.write("\\usepackage[utf8]{inputenc}\n")
        f.write("\\usepackage{booktabs}\n")
        f.write("\\usepackage{longtable}\n")
        f.write("\\usepackage{geometry}\n")
        f.write("\\geometry{margin=0.8in}\n")
        f.write("\\usepackage{rotating}\n")
        f.write("\\usepackage{pdflscape}\n")
        f.write("\\begin{document}\n\n")
        f.write("\\title{BVH Analysis Results - All Tables}\n")
        f.write("\\author{Generated by data\\_to\\_latex.py}\n")
        f.write("\\date{\\today}\n")
        f.write("\\maketitle\n\n")
        f.write("\\tableofcontents\n")
        f.write("\\clearpage\n\n")

        # Write each table as a section
        for table_info in table_data:
            f.write(f"\\section{{{table_info['section_title']}}}\n")
            f.write(table_info['latex_content'])
            f.write("\n\\clearpage\n\n")

        f.write("\\end{document}\n")

    print(f"Consolidated LaTeX document saved to: {latex_file}")


def main():
    parser = argparse.ArgumentParser(description="Convert CSV tables to LaTeX format - Ah-hyuck!")
    parser.add_argument(
        "--results_dir",
        type=Path,
        help="Path to results directory containing CSV files"
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        help="Output directory for LaTeX files (default: same as results_dir)"
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="*table*.csv",
        help="File pattern to match CSV files (default: *table*.csv)"
    )

    args = parser.parse_args()

    # Find results directory automatically if not specified
    if not args.results_dir:
        # Look for the most recent results directory
        base_dir = Path(".")
        possible_dirs = list(base_dir.glob("**/results"))
        if possible_dirs:
            args.results_dir = max(possible_dirs, key=lambda p: p.stat().st_mtime)
            print(f"Auto-detected results directory: {args.results_dir}")
        else:
            print("No results directory found! Please specify --results_dir")
            return

    results_dir = args.results_dir.resolve()
    output_dir = args.output_dir.resolve() if args.output_dir else results_dir

    if not results_dir.exists():
        print(f"Results directory not found: {results_dir}")
        return

    # Create output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # Define table configurations
    table_configs = {
        'statistical_results_table': {
            'caption': 'BVH Performance Comparison Results',
            'label': 'tab:statistical_results',
            'section_title': 'Statistical Results Table'
        },
        'comparison_results_table': {
            'caption': 'Collapsed vs k-way Algorithm Comparison Results',
            'label': 'tab:comparison_results',
            'section_title': 'Collapsed vs k-way Algorithm Comparison'
        },
        'dynamic_model_results_table': {
            'caption': 'Dynamic Model Analysis: Combined Construction + Traversal Time',
            'label': 'tab:dynamic_model_results',
            'section_title': 'Dynamic Model Analysis Results'
        },
        'dynamic_comparison_results_table': {
            'caption': 'Dynamic Comparison: Collapsed vs k-way Combined Time',
            'label': 'tab:dynamic_comparison_results',
            'section_title': 'Dynamic Comparison Results'
        }
    }

    # Find CSV files
    csv_files = list(results_dir.glob(args.pattern))
    if not csv_files:
        print(f"No CSV files found matching pattern '{args.pattern}' in {results_dir}")
        return

    print(f"Found {len(csv_files)} CSV files to process:")
    for csv_file in csv_files:
        print(f"  - {csv_file.name}")

    # Process each CSV file
    processed_tables = []

    for csv_file in csv_files:
        # Try to match with known table types
        table_config = None
        for config_key, config in table_configs.items():
            if config_key in csv_file.stem:
                table_config = config
                break

        # Use default config if no match found
        if not table_config:
            table_config = {
                'caption': f'Analysis Results Table: {csv_file.stem.replace("_", " ").title()}',
                'label': f'tab:{csv_file.stem}',
                'section_title': f'{csv_file.stem.replace("_", " ").title()}'
            }

        table_info = process_csv_to_latex(csv_file, output_dir, table_config)
        if table_info:
            processed_tables.append(table_info)

    # Create consolidated document
    if processed_tables:
        create_consolidated_latex_document(processed_tables, output_dir)
        print(f"Individual LaTeX files and consolidated document saved to: {output_dir}")
    else:
        print("No tables were processed successfully. Gawrsh!")


if __name__ == "__main__":
    main()
